# Generated by Django 5.2.14 on 2026-06-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_fotoproduto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoproduto',
            options={'ordering': ['ordem', '-criado_em'], 'verbose_name': 'Foto do Produto', 'verbose_name_plural': 'Fotos do Produto'},
        ),
    ]
