# Generated by Django 5.2.14 on 2026-06-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_fotoproduto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('atendimento', 'Em atendimento'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('cancelado', 'Cancelado')], default='novo', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
